- name:  Debian step 1 - Install packages
  become: true
  apt:
    name: ['apt-transport-https','ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    state: present
    update_cache: yes
    
    
- name: Debian step 2 - Add Docker’s official GPG key  
  become: true
  apt_key:
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present
  
  
- name: Debian step 3 - Download and create repo
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu  "{{ dist_release }}" stable
      state: present
  become: true
  become_method: sudo
  
  
- name: Debian step 4 - Install Docker Engine
  become: true
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'docker-ce-cli']
    state: present
    update_cache: yes
  register: docker_engine
  
  
- name: Debian step 5 - Restart the docker service
  become: true
  service:
      name: docker
      state: restarted
      enabled: yes
  when: docker_engine.changed
  
- name: Debian step 6 - Create the docker group
  become: true
  group:
      name: docker
      state: present