---
- hosts: web
  vars:
    http_port: 80
    max_clients: 200
    dist_release: "{{ ansible_distribution_release }}"
  tasks:
    
  - name: Install packages to allow apt to use a repository over HTTPS
    become: true
    apt:
      name: ['apt-transport-https','ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
      state: present
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
  - name: Add Docker’s official GPG key  
    become: true
    apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
    when: ansible_distribution == "Ubuntu"
    
  - name: set up the stable repository
    apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu  "{{ dist_release }}" stable
        state: present
    become: true
    become_method: sudo        
    when: ansible_distribution == "Ubuntu"
    
  - name: Install the latest version of Docker Engine
    become: true
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'docker-ce-cli']
      state: present
      update_cache: yes
    register: docker_engine
    when: ansible_distribution == "Ubuntu"
    
  - name: Restart the docker serviceif the docker engine package gets updated
    become: true
    service:
        name: docker
        state: restarted
        enabled: yes
    when: docker_engine.changed
    
  - name: Create the docker group
    become: true
    group:
        name: docker
        state: present
        
  - name: Add your user to the docker group
    become: true
    user:
        name: ubuntu
        groups: docker
        append: yes
    when: ansible_distribution == "Ubuntu"